# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-14 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0003_auto_20161014_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='name',
            field=models.CharField(max_length=300),
        ),
    ]
